title: Mahammad Arshad Ayub Shaik
email: mahammadarshadas@gmail.com
profile_picture: /images/profile-pic.jpg
description: > # this means to ignore newlines until "baseurl:"
  Personal website showcasing my data scientist portfolio, professional experience, and skills.
baseurl: "/blog.md"
url: "https://arshadsm.github.io" # the base hostname & protocol for your site
linkedin: https://www.linkedin.com/in/arshad-ayub01/
instagram: https://www.instagram.com/arshaditseems/

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Custom settings
projects:
  - title: MovieLens Recommendation System
    description: Recommends a similar movie that might interest the customer based on similarity index of movie user has just watched.
    link: /notebooks/notebook1.html
  - title: Identifying images using Computer Vision
    description: Identification of images using computer vision techniques such as OpenCV, etc.
    link: /notebooks/notebook2.html

skills:
  - Python
  - Data Analysis
  - Machine Learning
  - Data Visualization
  - SQL
  - R
