title: Mahammad Arshad Ayub Shaik
email: mahammadarshadas@gmail.com
profile_picture: /images/profile-pic.jpg
description: "Personal website showcasing my data scientist portfolio, professional experience, and skills."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arshadsm.github.io" # the base hostname & protocol for your site
linkedin: https://www.linkedin.com/in/arshad-ayub01/
instagram: https://www.instagram.com/arshaditseems/

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Custom settings
projects:
  - title: MovieLens Recommendation System
    description: "Recommends a similar movie that might interest the customer based on the similarity index of movies the user has just watched."
    link: /notebooks/MovieLens_Recommendation_System.html

skills:
  - "Databases & Languages: **Python, R, SAS, SQL, Oracle, Amazon Redshift, PostgreSQL, MS SQL Server, Teradata**"
  - "Statistical Methods: **ANOVA, Time Series, Hypothesis Testing, Bayes Law, Principal Component Analysis (PCA), Dimensionality Reduction, Cross-Validation, Auto-correlation, Confidence Intervals**"
  - "Machine Learning: **Regression Analysis, Bayesian Method, Decision Tree, Random Forests, SVM, Neural Network, Sentiment Analysis, K-Means Clustering, KNN, Ensemble Method, Deep Learning, Natural Language Processing (NLP)**"
  - "Hadoop Ecosystem: **Hadoop 2.x, Spark 2.x, MapReduce, Hive, HDFS, Sqoop, Flume**"
  - "Data Visualization: **Tableau, QlikView, PowerBI, Matplotlib, Seaborn, ggplot2**"
  - "Operating Systems: **Windows, UNIX/UNIX Shell Scripting, Linux**"
  - "Cloud Computing and Version Control Systems: **MS Azure, AWS - RedShift, EC2, EMR, S3, Git**"
  - "Soft Skills: **Leadership skills, Interpersonal, Oral and Written communication**"
