title: Mahammad Arshad Ayub Shaik
email: mahammadarshadas@gmail.com
profile_picture: /assets/images/profile-pic.jpg
description: > # this means to ignore newlines until "baseurl:"
  Personal website showcasing my data scientist portfolio, professional experience, and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arshadsm.github.io" # the base hostname & protocol for your site
linkedin: https://www.linkedin.com/in/your-linkedin-username/
instagram: https://www.instagram.com/your-instagram-username/

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Custom settings
projects:
  - title: Project 1
    description: Description of project 1.
    link: /notebooks/notebook1.html
  - title: Project 2
    description: Description of project 2.
    link: /notebooks/notebook2.html

skills:
  - Python
  - Data Analysis
  - Machine Learning
  - Data Visualization
  - SQL
